name: Deploy Website to FTP

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  ftp-deploy:
    name: Deploy to FTP Server
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history for better sync
      
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git**
            **/.github**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
            **/*.log
            **/README.md
            **/TESTING_*.md
            **/ROLLBACK_*.md
            **/backup*/**
            **/COMPLETE_BACKUP/**
            **/*backup*.html
            **/*test*.js
            **/*TEST*.js
          dangerous-clean-slate: false
          dry-run: false
